# Archivo: .github/workflows/pacman.yml
name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"  # Ejecuta cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: IsaacJimenezR
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark
            dist/pacman-contribution-graph-light.svg?palette=github-light

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
