# Archivo: .github/workflows/pacman.yml
name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Cada 6 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Pacman eating contributions
        uses: Platane/snk@v3
        with:
          github_user_name: IsaacJimenezR
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark&animation_duration=1&animation_type=pacman
            dist/pacman-light.svg?palette=github-light&animation_duration=1&animation_type=pacman
          
      - name: Push Pacman to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
